/*
Custom License for kfoozminus Projects
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/kfoozminus/booklist-controller/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// Jackpots returns a JackpotInformer.
	Jackpots() JackpotInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// Jackpots returns a JackpotInformer.
func (v *version) Jackpots() JackpotInformer {
	return &jackpotInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
