/*
Custom License for kfoozminus Projects
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	kfoozminusv1alpha1 "github.com/kfoozminus/booklist-controller/pkg/apis/kfoozminus/v1alpha1"
	versioned "github.com/kfoozminus/booklist-controller/pkg/client/clientset/versioned"
	internalinterfaces "github.com/kfoozminus/booklist-controller/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/kfoozminus/booklist-controller/pkg/client/listers/kfoozminus/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// JackpotInformer provides access to a shared informer and lister for
// Jackpots.
type JackpotInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.JackpotLister
}

type jackpotInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewJackpotInformer constructs a new informer for Jackpot type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewJackpotInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredJackpotInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredJackpotInformer constructs a new informer for Jackpot type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredJackpotInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KfoozminusV1alpha1().Jackpots(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KfoozminusV1alpha1().Jackpots(namespace).Watch(options)
			},
		},
		&kfoozminusv1alpha1.Jackpot{},
		resyncPeriod,
		indexers,
	)
}

func (f *jackpotInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredJackpotInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *jackpotInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&kfoozminusv1alpha1.Jackpot{}, f.defaultInformer)
}

func (f *jackpotInformer) Lister() v1alpha1.JackpotLister {
	return v1alpha1.NewJackpotLister(f.Informer().GetIndexer())
}
