/*
Custom License for kfoozminus Projects
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/kfoozminus/booklist-controller/pkg/client/clientset/versioned/typed/kfoozminus/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeKfoozminusV1alpha1 struct {
	*testing.Fake
}

func (c *FakeKfoozminusV1alpha1) Jackpots(namespace string) v1alpha1.JackpotInterface {
	return &FakeJackpots{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeKfoozminusV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
