/*
Custom License for kfoozminus Projects
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/kfoozminus/booklist-controller/pkg/apis/kfoozminus/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeJackpots implements JackpotInterface
type FakeJackpots struct {
	Fake *FakeKfoozminusV1alpha1
	ns   string
}

var jackpotsResource = schema.GroupVersionResource{Group: "kfoozminus.com", Version: "v1alpha1", Resource: "jackpots"}

var jackpotsKind = schema.GroupVersionKind{Group: "kfoozminus.com", Version: "v1alpha1", Kind: "Jackpot"}

// Get takes name of the jackpot, and returns the corresponding jackpot object, and an error if there is any.
func (c *FakeJackpots) Get(name string, options v1.GetOptions) (result *v1alpha1.Jackpot, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(jackpotsResource, c.ns, name), &v1alpha1.Jackpot{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Jackpot), err
}

// List takes label and field selectors, and returns the list of Jackpots that match those selectors.
func (c *FakeJackpots) List(opts v1.ListOptions) (result *v1alpha1.JackpotList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(jackpotsResource, jackpotsKind, c.ns, opts), &v1alpha1.JackpotList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.JackpotList{ListMeta: obj.(*v1alpha1.JackpotList).ListMeta}
	for _, item := range obj.(*v1alpha1.JackpotList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested jackpots.
func (c *FakeJackpots) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(jackpotsResource, c.ns, opts))

}

// Create takes the representation of a jackpot and creates it.  Returns the server's representation of the jackpot, and an error, if there is any.
func (c *FakeJackpots) Create(jackpot *v1alpha1.Jackpot) (result *v1alpha1.Jackpot, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(jackpotsResource, c.ns, jackpot), &v1alpha1.Jackpot{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Jackpot), err
}

// Update takes the representation of a jackpot and updates it. Returns the server's representation of the jackpot, and an error, if there is any.
func (c *FakeJackpots) Update(jackpot *v1alpha1.Jackpot) (result *v1alpha1.Jackpot, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(jackpotsResource, c.ns, jackpot), &v1alpha1.Jackpot{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Jackpot), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeJackpots) UpdateStatus(jackpot *v1alpha1.Jackpot) (*v1alpha1.Jackpot, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(jackpotsResource, "status", c.ns, jackpot), &v1alpha1.Jackpot{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Jackpot), err
}

// Delete takes name of the jackpot and deletes it. Returns an error if one occurs.
func (c *FakeJackpots) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(jackpotsResource, c.ns, name), &v1alpha1.Jackpot{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeJackpots) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(jackpotsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.JackpotList{})
	return err
}

// Patch applies the patch and returns the patched jackpot.
func (c *FakeJackpots) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Jackpot, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(jackpotsResource, c.ns, name, pt, data, subresources...), &v1alpha1.Jackpot{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Jackpot), err
}
