/*
Custom License for kfoozminus Projects
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/kfoozminus/booklist-controller/pkg/apis/kfoozminus/v1alpha1"
	scheme "github.com/kfoozminus/booklist-controller/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// JackpotsGetter has a method to return a JackpotInterface.
// A group's client should implement this interface.
type JackpotsGetter interface {
	Jackpots(namespace string) JackpotInterface
}

// JackpotInterface has methods to work with Jackpot resources.
type JackpotInterface interface {
	Create(*v1alpha1.Jackpot) (*v1alpha1.Jackpot, error)
	Update(*v1alpha1.Jackpot) (*v1alpha1.Jackpot, error)
	UpdateStatus(*v1alpha1.Jackpot) (*v1alpha1.Jackpot, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.Jackpot, error)
	List(opts v1.ListOptions) (*v1alpha1.JackpotList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Jackpot, err error)
	JackpotExpansion
}

// jackpots implements JackpotInterface
type jackpots struct {
	client rest.Interface
	ns     string
}

// newJackpots returns a Jackpots
func newJackpots(c *KfoozminusV1alpha1Client, namespace string) *jackpots {
	return &jackpots{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the jackpot, and returns the corresponding jackpot object, and an error if there is any.
func (c *jackpots) Get(name string, options v1.GetOptions) (result *v1alpha1.Jackpot, err error) {
	result = &v1alpha1.Jackpot{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("jackpots").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Jackpots that match those selectors.
func (c *jackpots) List(opts v1.ListOptions) (result *v1alpha1.JackpotList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.JackpotList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("jackpots").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested jackpots.
func (c *jackpots) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("jackpots").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a jackpot and creates it.  Returns the server's representation of the jackpot, and an error, if there is any.
func (c *jackpots) Create(jackpot *v1alpha1.Jackpot) (result *v1alpha1.Jackpot, err error) {
	result = &v1alpha1.Jackpot{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("jackpots").
		Body(jackpot).
		Do().
		Into(result)
	return
}

// Update takes the representation of a jackpot and updates it. Returns the server's representation of the jackpot, and an error, if there is any.
func (c *jackpots) Update(jackpot *v1alpha1.Jackpot) (result *v1alpha1.Jackpot, err error) {
	result = &v1alpha1.Jackpot{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("jackpots").
		Name(jackpot.Name).
		Body(jackpot).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *jackpots) UpdateStatus(jackpot *v1alpha1.Jackpot) (result *v1alpha1.Jackpot, err error) {
	result = &v1alpha1.Jackpot{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("jackpots").
		Name(jackpot.Name).
		SubResource("status").
		Body(jackpot).
		Do().
		Into(result)
	return
}

// Delete takes name of the jackpot and deletes it. Returns an error if one occurs.
func (c *jackpots) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("jackpots").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *jackpots) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("jackpots").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched jackpot.
func (c *jackpots) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Jackpot, err error) {
	result = &v1alpha1.Jackpot{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("jackpots").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
