/*
Custom License for kfoozminus Projects
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// JackpotListerExpansion allows custom methods to be added to
// JackpotLister.
type JackpotListerExpansion interface{}

// JackpotNamespaceListerExpansion allows custom methods to be added to
// JackpotNamespaceLister.
type JackpotNamespaceListerExpansion interface{}
